/**
 * Short motivational headlines (3–6 words) for waiting moments.
 * Shown during order preparation, loading, etc. No labels — headline only.
 */

export const MOTIVATIONAL_HEADLINES: string[] = [
  // Execution & focus
  'Execution beats theory.',
  'Build more. Talk less.',
  'Let results speak.',
  'Make ideas real.',
  'Work quietly. Win loudly.',
  'Small steps. Big impact.',
  'Done is greater than perfect.',
  'Focus. Finish. Repeat.',
  'Discipline creates freedom.',
  'Progress over perfection.',
  'Show up. Ship work.',
  'Consistency compounds results.',
  'Think bold. Build simple.',
  'Less noise. More work.',
  'Ideas are easy. Execution isn’t.',
  'Lead by your actions.',
  'Effort never goes unnoticed.',
  'Precision is power.',
  'Respect the craft.',
  'Learn. Iterate. Improve.',
  'Stay curious. Move fast.',
  'Quiet focus. Clear output.',
  'Choose progress today.',
  'Make the next move.',
  'Greatness loves preparation.',
  'Better every single day.',
  'Systems beat motivation.',
  'Energy follows focus.',
  'One thing at a time.',
  'Start small. Think big.',
  'Today’s work. Tomorrow’s results.',
  'Ship. Learn. Upgrade.',
  'Don’t wait. Create.',
  'Momentum beats motivation.',
  'Stay humble. Stay hungry.',
  'Excellence is a habit.',
  'Time rewards discipline.',
  'Show, don’t tell.',
  'Build what you wish existed.',
  'Stack tiny wins daily.',
  'Progress is the point.',
  'Calm mind. Sharp execution.',
  'Design with intent.',
  'Details define quality.',
  'Better done than dreamed.',
  'Focus is your superpower.',
  'Start now. Refine later.',
  'Small moves. Big shifts.',
  // Revenge via results (quiet success)
  'Let success answer everything.',
  'Win so loud they whisper.',
  'Silence now. Score later.',
  'Turn doubt into fuel.',
  'Remember who doubted you.',
  'Work hard. Prove quietly.',
  'Outsmart. Outwork. Outlast.',
  'Build what they said you couldn’t.',
  'Turn can’t into done.',
  'Let progress be your clapback.',
  'Results are the best reply.',
  'Make your work their lesson.',
  'Stay kind. Train ruthless.',
  'Take notes. Then take off.',
  'Don’t argue. Outperform.',
  'Grow past every critic.',
  'Keep receipts. Cash them later.',
  'Turn every no into numbers.',
  'Outgrow the room, not the work.',
  'The best payback is progress.',
  // More revenge via results
  'Win so big they blink.',
  'Turn doubt into deadlines.',
  'Collect doubts. Convert to wins.',
  'Let hard work avenge you.',
  'Let silence build momentum.',
  'Train until noise fades.',
  'Outgrow everyone’s expectations quietly.',
  'Turn every slight into fuel.',
  'Make your work the answer.',
  'They talk. You tally wins.',
  'Remember the laughs. Beat them.',
  'Let progress sting softly.',
  'They guess. You execute.',
  'Make impossible your habit.',
  'Turn side-eyes into applause.',
  'Turn gossip into greatness.',
  'Let discipline be your revenge.',
  'Replace arguments with outcomes.',
  'Upgrade while they underestimate.',
  'Patience now. Payback later.',
  'Keep receipts. Cash success.',
  'Channel anger into output.',
  'Don’t clap back. Level up.',
  'Turn every no into next.',
  'Quiet grind. Loud graduation.',
  'Let results break the script.',
  'Rise where they stayed still.',
  'Answer rumors with records.',
  'Turn pressure into performance.',
  'Prove them wrong. Stay kind.',
  'Make your graph the comeback.',
  'Turn shame into sharp focus.',
  'Turn shade into spotlight.',
  'Let consistency do the talking.',
  'Turn every doubt into data.',
  'Outlearn. Outbuild. Outlast.',
  'Let work rewrite your story.',
  'Outgrow every old version.',
  'Turn underestimation into edge.',
  'Keep moving. Let them watch.',
  'Success is the best revenge.',
];

export const REVENGE_QUOTES = MOTIVATIONAL_HEADLINES.slice(56);
